//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Invoice
    {
        public System.DateTime CreationDate { get; set; }
        public Nullable<decimal> TotalPriceHT { get; set; }

        public Nullable<decimal> TotalTVA { get; set; }
        [Required(ErrorMessage = "champ obligatoire")]
        public int IdClient { get; set; }

        public Nullable<decimal> TotalPrice { get; set; }
        public int Id { get; set; }
        [Required(ErrorMessage = "champ obligatoire")]
        public Nullable<int> status { get; set; }
        [Required(ErrorMessage ="champ obligatoire")]
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    }
}
