//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public Nullable<decimal> IdInvoice { get; set; }
        public string Code { get; set; }
        public int quantity { get; set; }
        public Nullable<decimal> totalPriceHT { get; set; }
        public Nullable<decimal> totalTVA { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> UnitPriceHT { get; set; }
        public int Id { get; set; }
    }
}
