//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Title { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<decimal> IdSupplier { get; set; }
        public string IdCategory { get; set; }
        public Nullable<decimal> IdCurrency { get; set; }
        public decimal MargeReduction { get; set; }
        public string Code { get; set; }
        public int Id { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> TVA { get; set; }
        public Nullable<int> State { get; set; }
    }
}
