//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Supplier
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "le champs titre est obligatoire")]
        public string Title { get; set; }
    
        public Nullable<System.DateTime> CreationDate { get; set; }
        [Required(ErrorMessage = "le champs titre est obligatoire")]
        public string Address { get; set; }
        [Required(ErrorMessage = "le champs titre est obligatoire")]
        [DataType(DataType.EmailAddress, ErrorMessage = "email invalide")]
        public string email { get; set; }
        [Required(ErrorMessage = "le champs titre est obligatoire")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Le numéro est invalide")]
        public string phone { get; set; }
        public Nullable<int> State { get; set; }
    }
}
